// This file is auto-generated by scripts/generateGithubProjects.js
// Do not edit by hand — commit generated file or change the generator.

export const githubProjects = [
  {
    "title": "Portfolio",
    "description": "My Personal Portfolio",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Portfolio",
      "external": "https://ajinkya-portfolio-eight.vercel.app"
    }
  },
  {
    "title": "Internship-Management-Portal-2.0",
    "description": "No description provided.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Internship-Management-Portal-2.0",
      "external": ""
    }
  },
  {
    "title": "Ajinkya-Nagarkar",
    "description": "No description provided.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Ajinkya-Nagarkar",
      "external": ""
    }
  },
  {
    "title": "Tic-Tac-Toe",
    "description": "No description provided.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Tic-Tac-Toe",
      "external": ""
    }
  },
  {
    "title": "Internship-Management-Portal",
    "description": "No description provided.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Internship-Management-Portal",
      "external": ""
    }
  },
  {
    "title": "ai-spatial-tour-assistant",
    "description": "A GIS project combining spatial data processing (KML/GeoJSON) with AI-powered location analysis.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/ai-spatial-tour-assistant",
      "external": ""
    }
  },
  {
    "title": "Natural-Language-SQL-Pipeline",
    "description": "Text-to-SQL Analytics Engine using Kimi K2 & DuckDB",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Natural-Language-SQL-Pipeline",
      "external": ""
    }
  },
  {
    "title": "Local-LLM-Schema-Architect",
    "description": "Automated ER Diagram generation using local LLMs (Ollama) and Streamlit.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Local-LLM-Schema-Architect",
      "external": ""
    }
  }
] as const;
