// This file is auto-generated by scripts/generateGithubProjects.js
// Do not edit by hand — commit generated file or change the generator.

export const githubProjects = [
  {
    "title": "Portfolio",
    "description": "My Personal Portfolio",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Portfolio",
      "external": "https://ajinkya-nagarkar.vercel.app/"
    }
  },
  {
    "title": "Geospatial Analytics Pipeline",
    "description": "Geospatial data pipeline demonstrating spatial analysis, geometry generation, and interactive visualization using PostGIS, KML, OpenLayers, and ArcGIS.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Geospatial-Analytics-Pipeline",
      "external": ""
    }
  },
  {
    "title": "AI Generated Leaflet Mapper",
    "description": "AI-assisted development of a Leaflet-based web mapping app using DYAD and a local LLM via Ollama.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/AI-generated-Leaflet-Mapper",
      "external": ""
    }
  },
  {
    "title": "AI Multimodal Map Annotator",
    "description": "Prompt-driven multimodal mapping experiment using Google AI Studio to annotate map images from coordinate inputs.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/AI-multimodal-Map-annotator",
      "external": ""
    }
  },
  {
    "title": "Ajinkya Nagarkar",
    "description": "No description provided.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Ajinkya-Nagarkar",
      "external": ""
    }
  },
  {
    "title": "Tic Tac Toe",
    "description": "No description provided.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Tic-Tac-Toe",
      "external": ""
    }
  },
  {
    "title": "Internship Management Portal",
    "description": "No description provided.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Internship-Management-Portal",
      "external": ""
    }
  },
  {
    "title": "Natural Language SQL Pipeline",
    "description": "Text-to-SQL Analytics Engine using Kimi K2 & DuckDB",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Natural-Language-SQL-Pipeline",
      "external": ""
    }
  },
  {
    "title": "Local LLM Schema Architect",
    "description": "Automated ER Diagram generation using local LLMs (Ollama) and Streamlit.",
    "tech": [],
    "links": {
      "github": "https://github.com/Ajinkya-Nagarkar/Local-LLM-Schema-Architect",
      "external": ""
    }
  }
] as const;
