/**
 * scripts/generateGithubProjects.js
 *
 * Usage:
 *   NODE_OPTIONS=--experimental-fetch node scripts/generateGithubProjects.js --username Ajinkya-Nagarkar
 * (On GitHub Actions, fetch is available by default on the runner.)
 *
 * What it does:
 *  - Reads config/content/projects/manual.ts and featured.ts
 *  - Extracts any links.github URLs (simple regex) and builds a Set to dedupe
 *  - Fetches public repos for the provided username (handles pagination)
 *  - Filters out forks and archived repos
 *  - Removes any repo whose html_url is present in manual/featured links
 *  - Writes config/content/projects/github.ts exporting githubProjects array
 *
 * Notes:
 *  - This script is conservative and outputs minimal fields to match your card shape:
 *    { title, description, tech: [], links: { github, external? } }
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const MANUAL_PATH = path.join(__dirname, "../src/config/content/projects/manual.ts");
const FEATURED_PATH = path.join(__dirname, "../src/config/content/projects/featured.ts");
const OUTPUT_PATH = path.join(__dirname, "../src/config/content/projects/github.ts");

// Basic arg parsing for --username
const argv = process.argv.slice(2);
let username = process.env.GITHUB_USER || process.env.INPUT_GITHUB_USER || null;
for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--username" && argv[i + 1]) {
        username = argv[i + 1];
        i++;
    }
}
if (!username) {
    console.error("ERROR: GitHub username not provided. Use --username or set env GITHUB_USER.");
    process.exit(2);
}

// Helper to extract github URLs from the manual/featured TS files
function extractGithubUrlsFromFile(filePath) {
    if (!fs.existsSync(filePath)) return [];
    const txt = fs.readFileSync(filePath, "utf8");
    // Simple regex: looks for github: "https://github.com/..." or github: 'https://github.com/...'
    const re = /github\s*:\s*["'](https?:\/\/github\.com\/[^"']+)["']/g;
    const out = [];
    let m;
    while ((m = re.exec(txt)) !== null) {
        out.push(m[1]);
    }
    return out;
}

function toTitleCaseFromSlug(slug) {
    return slug
        .replace(/[-_]/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase());
}


// Basic fetch wrapper using global fetch (Node 18+ on GH runners)
async function fetchJson(url, headers = {}) {
    const res = await fetch(url, { headers });
    if (!res.ok) {
        const txt = await res.text();
        throw new Error(`HTTP ${res.status} ${res.statusText} -> ${txt}`);
    }
    return res.json();
}

// Fetch all public repos for a user with pagination
async function fetchAllReposForUser(user, token = null) {
    const per_page = 100;
    let page = 1;
    let all = [];
    while (true) {
        const url = `https://api.github.com/users/${encodeURIComponent(user)}/repos?per_page=${per_page}&page=${page}&type=owner&sort=updated`;
        const headers = { Accept: "application/vnd.github+json" };
        if (token) headers.Authorization = `token ${token}`;
        const pageData = await fetchJson(url, headers);
        if (!Array.isArray(pageData) || pageData.length === 0) break;
        all = all.concat(pageData);
        if (pageData.length < per_page) break;
        page++;
    }
    return all;
}

function toOutputTs(projects) {
    // use JSON.stringify for safety, then tweak to look like TypeScript export
    // tech is an array; description may be null -> set default
    const safeProjects = projects.map((p) => ({
        title: p.title ?? "",
        description: p.description ?? "No description provided.",
        tech: p.tech ?? [],
        links: p.links ?? { github: p.github },
    }));
    const body = JSON.stringify(safeProjects, null, 2);
    return `// This file is auto-generated by scripts/generateGithubProjects.js\n// Do not edit by hand — commit generated file or change the generator.\n\nexport const githubProjects = ${body} as const;\n`;
}

(async () => {
    try {
        console.log("Reading manual + featured project files...");
        const manualUrls = extractGithubUrlsFromFile(MANUAL_PATH);
        const featuredUrls = extractGithubUrlsFromFile(FEATURED_PATH);
        const dedupeSet = new Set([...manualUrls, ...featuredUrls].filter(Boolean));
        console.log("Manual/Featured GitHub URLs found:", Array.from(dedupeSet));

        const token = process.env.GH_API_TOKEN || process.env.GITHUB_TOKEN || null;
        console.log(`Fetching public repos for user: ${username} ...`);
        const repos = await fetchAllReposForUser(username, token);
        console.log(`Fetched ${repos.length} repos.`);

        // Filter out forks & archived & skip repos that are in dedupeSet
        const filtered = repos
            .filter((r) => !r.fork && !r.archived)
            .filter((r) => {
                if (!r.html_url) return false;
                if (dedupeSet.has(r.html_url)) return false;
                return true;
            })
            .sort((a, b) => new Date(b.updated_at) - new Date(a.updated_at))
            .map((r) => ({
                title: toTitleCaseFromSlug(r.name),
                description: r.description || "No description provided.",
                tech: [],
                links: {
                    github: r.html_url,
                    external: r.homepage || "",
                },
            }));

        console.log(`After filter/dedup: ${filtered.length} repos will be exported.`);

        // Build TS output
        const out = toOutputTs(filtered);

        // Ensure output directory exists
        const outDir = path.dirname(OUTPUT_PATH);
        if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

        // Write file
        fs.writeFileSync(OUTPUT_PATH, out, "utf8");
        console.log(`Wrote ${OUTPUT_PATH}`);

        // Exit success
        process.exit(0);
    } catch (err) {
        console.error("Generator failed:", err);
        process.exit(3);
    }
})();
